c6o/docs

- content/guides/testdebug.md
- content/reference/cli.md
TODO: need to first confirm the installation process works on Linux/Mac/WSL (ex: which dependencies are required, etc).
> chore: Add basic CLI install/test instructions

- content/guides/firstapp.md
Reorganize and cleaned up Node-RED walkthrough.
> chore: Reorganize firstapp walkthrough

- content/reference/appspec.md
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
> New routing for ingress, incl. TCP

- content/guides/firstapp.md
Small corrections to language and spacing and I clarified some sentences.
> Small corrections to language and spacing.

- content/welcome/overview.md
Made the distinction between Cloud Applications and other things more apparent in the wording.
Made it clear that Cloud Applications are the "new" offering here and what they do to simplify and make things easier.
> Improved phrasing and rhetoric.

- content/_fragments/codezeroisos.md
Created a fragment that describes CodeZero as something you install into your cloud. I think this or something like this should follow the first "whatiscodezero" fragment.
> CodeZero as something you install

- content/reference/appspec.md
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
> Removing bad routes example

- content/references/appengine.md
Update AppEngine reference documentation to match new schema.
Fixes #41
> chore(AppEngine): update appengine reference to match new schema

- content/changelogs/cli.md
Update release notes for v0.2.6 of the CLI.
> docs(cli): Add v0.2.6 release notes

- content/references/teleport.md
Minimized mentions of kubefwd 
Corrected some typos
Added -m flag
Removed -w flag
Optional:
> Various edits.

- content/guides/getting-started.md
Removed the duplicated install cli instructions
> fix: Removed redundant instructions.

- content/references/intercept.md
Added more examples for intercept
Optional:
> chore: More examples.

- content/changelogs/cli.md
Release notes for 2.7
Optional:
> Added release 2.7 release notes

- content/concepts/teleport.md
Made the teleport description more clear around the solution it provides
Optional:
> chore: Made the teleport description clearer

- content/concepts/intercept.md
I don't believe that intercepting all traffic is an option.
Optional:
> chore: Removed "intercept all traffic"

- content/references/teleport.md
> chore: added teleport examples

- content/references/intercept.md
- content/references/teleport.md
> chore: Added sections on residue and cleanup

- index.html
> removed the extra https

- content/changelogs/cli.md
> release notes 0.2.8

- content/changelogs/cli.md
> Release notes for 1.0.0 and 1.0.1

- content/changelogs/cli.md
> Change logs for 1.0.3 and 1.0.4

- content/changelogs/cli.md
> update to 1.0.3 notes

- content/changelogs/cli.md
Release notes for version 1.1.0
> Version 1.1.0, volume mount release

- content/changelogs/cli.md
> update to the release notes

- content/changelogs/cli.md
> chore: Update known issues for version 1.1.0

- content/changelogs/cli.md
- content/concepts/teleport.md
- content/guides/installing-cli.md
- content/references/mount.md
- content/references/teleport.md
Changelog for CLI version v1.2.0.
This is the first release with the CodeZero daemon.
> chore(changelog): add CLI v1.2.0 release notes

- content/_sidebar.md
- content/guides/security.md
> chore: Added security guide

- content/welcome/overview.md
Changed some of the wording in the overview page
Optional:
> chore: changed some of the wording in the overview page

- content/guides/kubernetes-quickstart.md
- content/guides/using-cli.md
> chore: fixed some issues with digital ocean scripts and naming of clusters

- links/desktop.json
#2642 in the mono-repo
Optional:
> fix: links to command help.

- content/references/session-list.md
> fix: updated session list flags.

- content/changelogs/cli.md
We might need to start creating separate release notes for each tool... maybe a task for next release.
> feat(cli): Release Notes for 1.3.0

- content/changelogs/cli.md
fixes https://github.com/c6o/roadmap/issues/39
Optional:
> chore(cli): changelog update for 1.3.1

- content/guides/commands/intercept.md
- content/guides/commands/mount.md
- content/guides/installing.md
- content/tutorials/desktop-app.md
- content/tutorials/edge.md
Used this for the UX user testing session.
Optional:
> feat: Add a CodeZero Desktop app tutorial

- content/guides/installing.md
- content/tutorials/desktop-app.md
> chore: Add a note about the OS requirements for the Desktop app

- content/changelogs/cli.md
Release notes for version 1.3.2
fixes: https://github.com/c6o/roadmap/issues/40 https://github.com/c6o/roadmap/issues/41
> chore(changelogs): add release 1.3.2 changelogs

- content/changelogs/cli.md
> chore(changelogs): add known issue to v1.3.2

- content/tutorials/_fragments/prerequisites.md
- content/tutorials/sample-project.md
This change emphasizes going through the entire README in the tutorial
Optional:
> chore: Update the tutorial for running the sample project

- content/tutorials/desktop-app.md
- content/tutorials/edge.md
- content/tutorials/sample-project.md
- content/welcome/about-us.md
- content/welcome/overview.md
> chore: Move the sample project tutorial into the docs

- content/tutorials/desktop-app.md
- content/tutorials/edge.md
- content/tutorials/sample-project.md
> chore: Update the Developing Edge Service tutorial

- content/tutorials/desktop-app.md
- content/tutorials/edge.md
> chore: More updates to the tutorials

- content/tutorials/desktop-app.md
- content/tutorials/edge.md
> chore: Tutorial documentation updates

- content/guides/development-profiles.md
- content/tutorials/desktop-app.md
> chore: Update docs to include .yaml file extension in the desktop tutorial

- .github/linters/.markdownlint.yaml
- .github/workflows/megalinter.yaml
Signed-off-by: Tyler Witlin <tyler@codezero.io>
This change allows for automated checking of markdown style/syntax and spelling while also opening PRs to fix issues that it detects.
Optional:
> feat: add megalinter

- apps/references/appengine.md
- content/_fragments/app-install.md
- content/_fragments/app-requirements.md
- content/guides/commands/configuration.md
- content/guides/commands/intercept.md
- content/guides/commands/mount.md
- content/guides/commands/teleport.md
- content/guides/installing.md
- content/guides/using-cli.md
> feat: Update the CodeZero installation instructions

- content/changelogs/cli.md
> release(1.6.0): release notes

- content/_sidebar.md
- content/tutorials/core.md
I added a Developing Core Services tutorial as a follow-on to AJ's Developing Edge Services tutorial.
Optional:
> chore: developing with core services.

- content/_sidebar.md
- content/guides/commands/mount.md
- content/tutorials/core.md
- content/tutorials/edge.md
- content/tutorials/mount.md
> feat: Developing with Remote Volumes (Mount) tutorial

- content/guides/installing.md
Signed-off-by: Tyler Witlin <tyler@codezero.io>
> chore: add instructions to install a specific version

- content/changelogs/cli.md
> chore(changelogs): add 1.7.0 changelogs

- content/changelogs/cli.md
> chore(changelogs): add 1.7.1 changelog

- content/changelogs/cli.md
> chore(release): 1.8.0 release notes

- docs/guides/getting-started.md
fixed Typo and capitalization in Getting Started guide
> Update getting-started.md - typos and capitalization

- docs/welcome/versions.md
corrected some grammar re: comprises vs "comprised of"
> Update versions.md - minor grammar

- docs/welcome/overview.md
added short description under the diagram
> Update overview.md - added description and 2-way arrows

- docs/guides/getting-started.md
Added links to the relevant docs pages on site.
> Update getting-started.md - hyperlinks added

- docs/references/changelog.md
Simpler upgrade process for <2.3.0
> update 2.3.0 release process

- docs/references/changelog.md
Added release dates and note that we have a 2 week release cadence
> Update changelog.md - added release dates

- docs/guides/teamspace-setup.md
Update with all information about load balancer setups
> add info about load balancer setups

- docs/guides/installing.mdx
- added Windows to the list of requirements and 
- minor change to the wording describing using a supported package manager or the install script
> Update installing.mdx - minor installer wording updates

- docs/tutorials/consume.mdx
> add guide to consume external database

- docs/guides/installing.mdx
fixes #issue
You can also reference issues in other repos (including private repos)
fixes org/repo#issue
> Updated Title for Installing Local Agent

- docs/guides/installing.mdx
Article title was too long - wrapped in sidebar
> Update Title - shorten title for index

- docs/guides/teamspace-setup.md
Added note to highlight Helm Chart info on GitHub re: additional annotations
> Update teamspace-setup.md - highlight Helm Chart details

- docs/references/changelog.md
and minor text edits to release notes
> Update changelog.md - adjust homebrew install command

- docs/references/architecture.md
moved HUB, SYSTEM, OPERATOR to the top, LOCAL below, clarified some of the language.
fixes #issue
You can also reference issues in other repos (including private repos)
fixes org/repo#issue
> Update architecture.md - re-organized Arch diagram, improved descriptions

- docs/guides/teamspace-setup.md
removed old references to Orchestrator
> Update teamspace-setup.md - remove Orchestrator references

- docs/guides/using-ui.mdx
- Adjusted title
- tweaked language
- added note about curl command needing customization depending on service
> Update using-ui.mdx - edits to Desktop App details

- docs/overview.md
tried to make the opening lines simpler & "punchier" a'la Georg
> Simplified the initial paragraph

- docs/overview.md
overview.md - added relative links to How-To and References sections in the docs
> Update docs - added links for How-To and References

- docs/overview.md
Update overview.md - added a few more links and tweaks - missed Concepts and Getting Started links in the previous update - added "Zero Environment" to the description of Logical Ephemeral Environment.
> docs update overview.md - added a few more links and tweaks

- docs/tutorial.mdx
addded download link to tutorial.mdx
> addded download link to tutorial.mdx

- docs/getting-started/teamspace-setup.md
Need to add a path because because `/` responds with 400
> add health check path

- docs/getting-started/vscode.md
added feedback email link for VSCode extension
> Update vscode.md - added feedback email

- docs/concepts/serve.mdx
Added more details to the Benefits of Serve and Details (under the hood) explanations
> Expanded serve.mdx docs

- docs/references/architecture.md
change old text reference System to newer "Space Agent" to match the updated Excalidraw diagram
> updated System to SpaceAgent

- docs/guides/troubleshooting.md
- how to terminate a Served Variant
fixes #issue
You can also reference issues in other repos (including private repos)
fixes org/repo#issue
> troubleshooting.md - how to terminate a Served Variant

- docs/guides/installing-spaceagent-terraform.mdx
Add docs for installing-spaceagent-terraform.mdx
need to add link for https://registry.terraform.io/providers/hashicorp/helm/latest/docs
> Add docs for installing-spaceagent-terraform.mdx

- docs/guides/troubleshooting.md
Update troubleshooting.md with cmd to delete dead serves (service-b)
> Update troubleshooting.md with cmd to delete dead serves (service-b)
